---
prerequisites:
  - apt-transport-https
  - ca-certificates
  - curl 
  - gnupg-agent
  - software-properties-common

docker_key: https://download.docker.com/linux/ubuntu/gpg 
docker_repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
docker_list:
  - docker-ce 
  - docker-ce-cli 
  - containerd.io