- name: Install pip3 
  apt:
    name: python3-pip
    state: present 
    
- name: Install docker pip package 
  pip:
    name: docker 
    state: present 

- name: run clair-db container 
  docker_container:
    name: db 
    image: arminc/clair-db
    ports:
    - "5432:5432"

- name: run clair local-scan container 
  docker_container:
    name: clair 
    image: arminc/clair-local-scan
    ports:
    - "6060:6060"
    links: 
    - db:postgres

