---
- name: restart containerd 
  service:
    name: containerd 
    state: restarted 
    enabled: True

- name: restart kubelet
  service:
    name: kubelet
    state: restarted 
    enabled: True 

- name: sysctl system 
  command: "sysctl --system"